pipeline {
    agent any
 	options {
   	 skipDefaultCheckout true
  	}
    stages {
        stage('Build') {
            steps {
		checkout([$class: 'GitSCM', branches: [[name: '*/master']],
     					    userRemoteConfigs: [[url: 'https://github.com/RatonII/ansible_roles.git']]])	
                echo 'Building..'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}
